# Generated by Django 4.2.11 on 2025-04-02 10:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("description1", models.TextField()),
                ("description2", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("image1", models.ImageField(upload_to="about_images/")),
                ("image2", models.ImageField(upload_to="about_images/")),
                ("alt_image1", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_image2", models.CharField(blank=True, max_length=255, null=True)),
                ("rating", models.IntegerField(default=5)),
            ],
            bases=(models.Model, core.models.OptimizedImageMixin),
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cab_type", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("content", models.TextField()),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    core.models.OptimizedImageField(
                        blank=True, null=True, upload_to="service/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="slider_images/")),
                ("rating", models.IntegerField(default=5)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            bases=(models.Model, core.models.OptimizedImageMixin),
        ),
        migrations.CreateModel(
            name="Cab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price_per_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="cab_images/")),
                ("description", models.TextField()),
                ("capacity", models.CharField(max_length=50)),
                ("cab_type", models.CharField(max_length=100)),
                (
                    "amenities",
                    models.ManyToManyField(related_name="cabs", to="core.amenity"),
                ),
            ],
            bases=(models.Model, core.models.OptimizedImageMixin),
        ),
    ]
