# Generated by Django 4.2.11 on 2025-10-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="features/")),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order"],},
        ),
        migrations.RemoveField(model_name="amenity", name="icon",),
        migrations.AddField(
            model_name="amenity",
            name="image",
            field=models.ImageField(default="exit", upload_to="icon/"),
            preserve_default=False,
        ),
    ]
