# Generated by Django 4.2.11 on 2025-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_feature_remove_amenity_icon_amenity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
