# Generated by Django 4.2.11 on 2025-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_type", models.CharField(max_length=20)),
                ("pickup_location", models.CharField(max_length=50)),
                ("dropoff_location", models.CharField(max_length=50)),
                ("transport_type", models.CharField(max_length=20)),
                ("adults", models.IntegerField()),
                ("children", models.IntegerField()),
                ("luggage", models.IntegerField()),
                ("pickup_time", models.CharField(blank=True, max_length=5)),
                ("return_time", models.CharField(blank=True, max_length=5)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("country_code", models.CharField(max_length=5)),
                ("phone", models.CharField(max_length=15)),
                ("notes", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
