# Generated by Django 5.2.1 on 2025-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxiData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_type", models.CharField(max_length=100)),
                ("pickup_location", models.CharField(max_length=100)),
                ("dropoff_location", models.CharField(max_length=100)),
                ("transport_type", models.CharField(max_length=100)),
                ("adults", models.FloatField()),
                ("children", models.FloatField()),
                ("pickup_time", models.FloatField()),
                ("return_time", models.FloatField()),
                ("price", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="booking",
            name="dropoff_location",
            field=models.CharField(
                choices=[
                    ("BEAUVAIS", "BEAUVAIS"),
                    ("CDG", "CDG"),
                    ("Disneyland", "Disneyland"),
                    ("ORLY (Orly Airport)", "ORLY (Orly Airport)"),
                    ("Paris hotels / Train Stations", "Paris hotels / Train Stations"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("BEAUVAIS", "BEAUVAIS"),
                    ("Bayeux", "Bayeux"),
                    (
                        "CDG(Charles de Gaulle Airport)",
                        "CDG(Charles de Gaulle Airport)",
                    ),
                    ("Fontainebleau", "Fontainebleau"),
                    ("ORLY (Orly Airport)", "ORLY (Orly Airport)"),
                    ("Paris hotels / Train Stations", "Paris hotels / Train Stations"),
                    ("Reims", "Reims"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="transport_type",
            field=models.CharField(
                choices=[("Car", "Car"), ("Van", "Van")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="trip_type",
            field=models.CharField(
                choices=[("One Way", "One Way"), ("Round Trip", "Round Trip")],
                max_length=20,
            ),
        ),
    ]
