# Generated by Django 5.2.1 on 2025-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_taxidata_alter_booking_dropoff_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxidata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
