# Generated by Django 4.2.11 on 2025-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_taxidata_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="dropoff_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="dropoff_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="dropoff_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="dropoff_location",
            field=models.CharField(
                choices=[
                    ("BEAUVAIS", "BEAUVAIS"),
                    ("CDG", "CDG"),
                    ("Disneyland", "Disneyland"),
                    ("ORLY (Orly Airport)", "ORLY (Orly Airport)"),
                    ("Paris hotels / Train Stations", "Paris hotels / Train Stations"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("BEAUVAIS", "BEAUVAIS"),
                    ("Bayeux", "Bayeux"),
                    (
                        "CDG(Charles de Gaulle Airport)",
                        "CDG(Charles de Gaulle Airport)",
                    ),
                    ("Fontainebleau", "Fontainebleau"),
                    ("ORLY (Orly Airport)", "ORLY (Orly Airport)"),
                    ("Paris hotels / Train Stations", "Paris hotels / Train Stations"),
                    ("Reims", "Reims"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
