# Generated by Django 4.2.11 on 2025-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_dropoff_address_booking_dropoff_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="checkout_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="promo_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="dropoff_location",
            field=models.CharField(
                choices=[
                    ("BEAUVAIS", "BEAUVAIS"),
                    ("Bayeux", "Bayeux"),
                    (
                        "CDG(Charles de Gaulle Airport)",
                        "CDG(Charles de Gaulle Airport)",
                    ),
                    ("Fontainebleau", "Fontainebleau"),
                    ("ORLY (Orly Airport)", "ORLY (Orly Airport)"),
                    ("Paris hotels / Train Stations", "Paris hotels / Train Stations"),
                    ("Reims", "Reims"),
                    ("CDG", "CDG"),
                    ("Disneyland", "Disneyland"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("BEAUVAIS", "BEAUVAIS"),
                    ("Bayeux", "Bayeux"),
                    (
                        "CDG(Charles de Gaulle Airport)",
                        "CDG(Charles de Gaulle Airport)",
                    ),
                    ("Fontainebleau", "Fontainebleau"),
                    ("ORLY (Orly Airport)", "ORLY (Orly Airport)"),
                    ("Paris hotels / Train Stations", "Paris hotels / Train Stations"),
                    ("Reims", "Reims"),
                    ("CDG", "CDG"),
                    ("Disneyland", "Disneyland"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
