# Generated by Django 4.2.11 on 2025-06-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_checkout_date_booking_promo_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking.promocode",
            ),
        ),
    ]
