# Generated by Django 4.2.11 on 2025-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_booking_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booster_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="checkin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="flight_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
