# Generated by Django 4.2.11 on 2025-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_booking_booster_seats_booking_checkin_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="transport_type",
            field=models.CharField(
                choices=[("Car", "Car"), ("Van", "Van")], default="Car", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="trip_type",
            field=models.CharField(
                choices=[("One Way", "One Way"), ("Round Trip", "Round Trip")],
                default="One Way",
                max_length=20,
            ),
        ),
    ]
