# Generated by Django 4.2.11 on 2025-08-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("One Way", "One Way"), ("Round Trip", "Round Trip")],
                        default="One Way",
                        max_length=20,
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("Car", "Car"), ("Van", "Van")],
                        default="Car",
                        max_length=20,
                    ),
                ),
                (
                    "pickup_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dropoff_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pickup_latitude", models.FloatField(blank=True, null=True)),
                ("pickup_longitude", models.FloatField(blank=True, null=True)),
                ("dropoff_latitude", models.FloatField(blank=True, null=True)),
                ("dropoff_longitude", models.FloatField(blank=True, null=True)),
                ("adults", models.IntegerField()),
                ("children", models.IntegerField(default=0)),
                ("luggage", models.IntegerField(default=0)),
                ("pickup_time", models.CharField(blank=True, max_length=5)),
                ("return_time", models.CharField(blank=True, max_length=5)),
                ("checkout_date", models.DateField(blank=True, null=True)),
                ("checkin_date", models.DateField(blank=True, null=True)),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("booster_seats", models.PositiveIntegerField(default=0)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("country_code", models.CharField(max_length=5)),
                ("phone", models.CharField(max_length=15)),
                ("notes", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Night Surcharge", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "night_charge",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("discount_percentage", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TripLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="book.booking",
                    ),
                ),
                (
                    "dropoff_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tripleg_dropoffs",
                        to="book.location",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tripleg_pickups",
                        to="book.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("Car", "Car"), ("Van", "Van")], max_length=50
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("One Way", "One Way"), ("Round Trip", "Round Trip")],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dropoff_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropoff_prices",
                        to="book.location",
                    ),
                ),
                (
                    "pickup_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_prices",
                        to="book.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="dropoff_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dropoff_bookings",
                to="book.location",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_bookings",
                to="book.location",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book.promocode",
            ),
        ),
    ]
