# Generated by Django 4.2.11 on 2025-08-08 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking", options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(name="location", options={"ordering": ("name",)},),
        migrations.AlterModelOptions(
            name="pricetable",
            options={
                "ordering": (
                    "pickup_location__name",
                    "dropoff_location__name",
                    "transport_type",
                    "trip_type",
                )
            },
        ),
        migrations.AlterModelOptions(
            name="pricingrule", options={"ordering": ("-active", "name")},
        ),
        migrations.AlterModelOptions(
            name="promocode", options={"ordering": ("-active", "-valid_until")},
        ),
        migrations.AlterModelOptions(
            name="tripleg", options={"ordering": ("booking", "sequence")},
        ),
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="luggage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_time",
            field=models.CharField(
                blank=True,
                choices=[("0", "Between 10 PM - 6 AM"), ("1", "Between 6 AM - 10 PM")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-calculated from PriceTable + PricingRule.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="return_time",
            field=models.CharField(
                blank=True,
                choices=[("0", "Between 10 PM - 6 AM"), ("1", "Between 6 AM - 10 PM")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pricetable",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricetable",
            unique_together={
                ("pickup_location", "dropoff_location", "transport_type", "trip_type")
            },
        ),
        migrations.AddIndex(
            model_name="pricetable",
            index=models.Index(
                fields=["pickup_location", "dropoff_location"],
                name="book_pricet_pickup__3893fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricetable",
            index=models.Index(
                fields=["transport_type", "trip_type"],
                name="book_pricet_transpo_dbcdfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tripleg",
            index=models.Index(
                fields=["booking", "sequence"], name="book_triple_booking_7b65f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripleg",
            index=models.Index(
                fields=["pickup_location", "dropoff_location"],
                name="book_triple_pickup__7494e3_idx",
            ),
        ),
    ]
