# Generated by Django 4.2.11 on 2025-08-08 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_booking_passagers_alter_booking_adults"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="passagers",),
        migrations.AddField(
            model_name="pricingrule",
            name="extra_per_passenger_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
