# Generated by Django 4.2.11 on 2025-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_remove_booking_passagers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripleg",
            name="dropoff_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tripleg",
            name="dropoff_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tripleg",
            name="dropoff_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tripleg",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tripleg",
            name="pickup_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tripleg",
            name="pickup_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
