# Generated by Django 4.2.11 on 2025-08-09 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_tripleg_dropoff_address_tripleg_dropoff_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("One Way", "One Way"), ("Round Trip", "Round Trip")],
                        max_length=20,
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("Car", "Car"), ("Van", "Van")],
                        default="Car",
                        max_length=20,
                    ),
                ),
                ("pax_min", models.PositiveIntegerField(default=1)),
                ("pax_max", models.PositiveIntegerField(default=3)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_destination",
                        to="book.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_origin",
                        to="book.location",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "origin__name",
                    "destination__name",
                    "trip_type",
                    "transport_type",
                    "pax_min",
                ),
            },
        ),
        migrations.RemoveField(model_name="tripleg", name="dropoff_latitude",),
        migrations.RemoveField(model_name="tripleg", name="dropoff_longitude",),
        migrations.RemoveField(model_name="tripleg", name="pickup_latitude",),
        migrations.RemoveField(model_name="tripleg", name="pickup_longitude",),
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="night_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.DeleteModel(name="PriceTable",),
        migrations.AddIndex(
            model_name="pricematrix",
            index=models.Index(
                fields=["origin", "destination", "trip_type", "transport_type"],
                name="book_pricem_origin__913e11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricematrix",
            index=models.Index(
                fields=["pax_min", "pax_max"], name="book_pricem_pax_min_06c5c3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricematrix",
            unique_together={
                (
                    "origin",
                    "destination",
                    "trip_type",
                    "transport_type",
                    "pax_min",
                    "pax_max",
                )
            },
        ),
    ]
