# Generated by Django 4.2.11 on 2025-10-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_pricematrix_remove_tripleg_dropoff_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Location Categories",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="location", options={"ordering": ("category__name", "name")},
        ),
        migrations.AddField(
            model_name="location",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="book.locationcategory",
            ),
        ),
    ]
