# Generated by Django 4.2.11 on 2025-10-06 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_locationcategory_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="location", options={"ordering": ("name",)},),
        migrations.RemoveField(model_name="location", name="category",),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_locations",
                to="book.location",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="pickup_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="return_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="LocationCategory",),
    ]
