# Generated by Django 4.2.11 on 2025-10-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_alter_location_options_remove_location_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailedLocation",
            fields=[],
            options={
                "verbose_name": "Hotel / Train Station",
                "verbose_name_plural": "Hotels & Train Stations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("book.location",),
        ),
        migrations.CreateModel(
            name="MainLocation",
            fields=[],
            options={
                "verbose_name": "Main Location / Group",
                "verbose_name_plural": "Main Locations / Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("book.location",),
        ),
        migrations.RemoveIndex(
            model_name="pricematrix", name="book_pricem_pax_min_06c5c3_idx",
        ),
        migrations.RemoveIndex(
            model_name="tripleg", name="book_triple_pickup__7494e3_idx",
        ),
        migrations.RemoveField(model_name="booking", name="dropoff_latitude",),
        migrations.RemoveField(model_name="booking", name="dropoff_longitude",),
        migrations.RemoveField(model_name="booking", name="pickup_latitude",),
        migrations.RemoveField(model_name="booking", name="pickup_longitude",),
        migrations.AddField(
            model_name="location",
            name="is_main_location",
            field=models.BooleanField(
                default=True,
                help_text="Check this for main locations or groups like 'Paris hotels'.",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_locations",
                to="book.location",
                verbose_name="Main Location Group",
            ),
        ),
    ]
