# Generated by Django 4.2.11 on 2025-10-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_detailedlocation_mainlocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="is_main_location",
            field=models.BooleanField(
                default=True,
                help_text="Check this for main locations (e.g., CDG) or groups (e.g., Paris Hotels).",
            ),
        ),
        migrations.AddIndex(
            model_name="pricematrix",
            index=models.Index(
                fields=["pax_min", "pax_max"], name="book_pricem_pax_min_06c5c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripleg",
            index=models.Index(
                fields=["pickup_location", "dropoff_location"],
                name="book_triple_pickup__7494e3_idx",
            ),
        ),
    ]
