# Generated by Django 4.2.11 on 2025-10-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_alter_location_is_main_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="baby_seats",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
